// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz69neYerD4YVIFwINSnRPza5o1I4IoNI',
    appId: '1:929378992478:web:5879fea57c0cb2e389cfcf',
    messagingSenderId: '929378992478',
    projectId: 'crud-flutter-3d6a1',
    authDomain: 'crud-flutter-3d6a1.firebaseapp.com',
    storageBucket: 'crud-flutter-3d6a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9T3jxNMFGMJHcHc3Tjnn-ndOLbQDt8cs',
    appId: '1:929378992478:android:f0637415543fe7d089cfcf',
    messagingSenderId: '929378992478',
    projectId: 'crud-flutter-3d6a1',
    storageBucket: 'crud-flutter-3d6a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtbfuNPTW4NQLLBXmSH-th-NPDU93ASD8',
    appId: '1:929378992478:ios:41248d7836c629da89cfcf',
    messagingSenderId: '929378992478',
    projectId: 'crud-flutter-3d6a1',
    storageBucket: 'crud-flutter-3d6a1.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtbfuNPTW4NQLLBXmSH-th-NPDU93ASD8',
    appId: '1:929378992478:ios:41248d7836c629da89cfcf',
    messagingSenderId: '929378992478',
    projectId: 'crud-flutter-3d6a1',
    storageBucket: 'crud-flutter-3d6a1.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz69neYerD4YVIFwINSnRPza5o1I4IoNI',
    appId: '1:929378992478:web:288268e61542a46189cfcf',
    messagingSenderId: '929378992478',
    projectId: 'crud-flutter-3d6a1',
    authDomain: 'crud-flutter-3d6a1.firebaseapp.com',
    storageBucket: 'crud-flutter-3d6a1.firebasestorage.app',
  );
}
